version: '3.4'
services:
  backend:
    build:
      context: ./
    volumes:
      - './src:/app/src'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
    networks:
      - webnet

  db:
    image: mongo:4.2.0-rc2-bionic
    volumes:
      - './data:/data'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
