version: '3.4'
services:
  backend:
    build:
      context: ./
    volumes:
      - './src:/app/src'
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
